package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

type goSchemaKind uint8

const (
	goSchemaAny goSchemaKind = iota
	goSchemaBool
	goSchemaInt
	goSchemaFloat
	goSchemaString
	goSchemaSlice
	goSchemaStruct
)

type goSchema struct {
	kind   goSchemaKind
	elem   *goSchema
	fields []goFieldSchema
}

type goFieldSchema struct {
	key     string
	typ     *goSchema
	comment string
}

type goTypeDecl struct {
	name   string
	fields []goRenderedField
}

type goRenderedField struct {
	name    string
	typeRef string
	tag     string
	comment string
}

type goRenderer struct {
	names map[*goSchema]string
	used  map[string]int
	decls []goTypeDecl
}

func generateGoDefinitions(v value, packageName, rootName string) ([]byte, error) {
	schema := inferGoSchema(v)
	rootName = goIdentifier(rootName, true)
	renderer := goRenderer{
		names: make(map[*goSchema]string),
		used:  make(map[string]int),
	}
	rootRef := renderer.renderType(schema, rootName)

	var src bytes.Buffer
	src.WriteString("// Code generated by json-convert. DO NOT EDIT.\n\n")
	src.WriteString("package ")
	src.WriteString(packageName)
	src.WriteString("\n\n")
	if schema.kind != goSchemaStruct {
		fmt.Fprintf(&src, "type %s %s\n", rootName, rootRef)
		if len(renderer.decls) > 0 {
			src.WriteByte('\n')
		}
	}
	for i, decl := range renderer.decls {
		if i > 0 {
			src.WriteByte('\n')
		}
		renderTypeDecl(&src, decl)
	}

	formatted, err := format.Source(src.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format Go output: %w", err)
	}
	return formatted, nil
}

func renderTypeDecl(buf *bytes.Buffer, decl goTypeDecl) {
	fmt.Fprintf(buf, "type %s struct {\n", decl.name)
	for _, field := range decl.fields {
		writeGoComment(buf, field.comment, "\t")
		fmt.Fprintf(buf, "\t%s %s `%s`\n", field.name, field.typeRef, field.tag)
	}
	buf.WriteString("}\n")
}

func writeGoComment(buf *bytes.Buffer, text, indent string) {
	if text == "" {
		return
	}
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			buf.WriteString(indent)
			buf.WriteString("//\n")
			continue
		}
		buf.WriteString(indent)
		buf.WriteString("// ")
		buf.WriteString(line)
		buf.WriteByte('\n')
	}
}

func inferGoSchema(v value) *goSchema {
	switch v.kind {
	case kindBool:
		return &goSchema{kind: goSchemaBool}
	case kindNumber:
		if isIntegerToken(v.text) {
			return &goSchema{kind: goSchemaInt}
		}
		return &goSchema{kind: goSchemaFloat}
	case kindString:
		return &goSchema{kind: goSchemaString}
	case kindArray:
		schema := &goSchema{kind: goSchemaSlice, elem: &goSchema{kind: goSchemaAny}}
		if len(v.array) == 0 {
			return schema
		}
		schema.elem = inferGoSchema(v.array[0])
		for i := 1; i < len(v.array); i++ {
			schema.elem = mergeGoSchema(schema.elem, inferGoSchema(v.array[i]))
		}
		return schema
	case kindObject:
		fields := make([]goFieldSchema, 0, len(v.object))
		index := make(map[string]int, len(v.object))
		for _, member := range v.object {
			field := goFieldSchema{
				key:     member.key,
				typ:     inferGoSchema(member.value),
				comment: memberComment(member),
			}
			if i, ok := index[member.key]; ok {
				fields[i].typ = mergeGoSchema(fields[i].typ, field.typ)
				if fields[i].comment == "" {
					fields[i].comment = field.comment
				}
				continue
			}
			index[member.key] = len(fields)
			fields = append(fields, field)
		}
		return &goSchema{kind: goSchemaStruct, fields: fields}
	default:
		return &goSchema{kind: goSchemaAny}
	}
}

func mergeGoSchema(left, right *goSchema) *goSchema {
	if left == nil {
		return right
	}
	if right == nil {
		return left
	}
	if left.kind == goSchemaAny || right.kind == goSchemaAny {
		return &goSchema{kind: goSchemaAny}
	}
	if left.kind == right.kind {
		switch left.kind {
		case goSchemaSlice:
			return &goSchema{kind: goSchemaSlice, elem: mergeGoSchema(left.elem, right.elem)}
		case goSchemaStruct:
			fields := append([]goFieldSchema(nil), left.fields...)
			index := make(map[string]int, len(fields))
			for i, field := range fields {
				index[field.key] = i
			}
			for _, field := range right.fields {
				if i, ok := index[field.key]; ok {
					fields[i].typ = mergeGoSchema(fields[i].typ, field.typ)
					if fields[i].comment == "" {
						fields[i].comment = field.comment
					}
					continue
				}
				index[field.key] = len(fields)
				fields = append(fields, field)
			}
			return &goSchema{kind: goSchemaStruct, fields: fields}
		default:
			return left
		}
	}
	if left.kind == goSchemaInt && right.kind == goSchemaFloat || left.kind == goSchemaFloat && right.kind == goSchemaInt {
		return &goSchema{kind: goSchemaFloat}
	}
	return &goSchema{kind: goSchemaAny}
}

func memberComment(member member) string {
	var parts []string
	comments := append([]comment(nil), member.leadingComments...)
	comments = append(comments, member.trailingComments...)
	for _, c := range comments {
		if text := cleanComment(c.raw); text != "" {
			parts = append(parts, text)
		}
	}
	return strings.Join(parts, "\n")
}

func isIntegerToken(text []byte) bool {
	if len(text) == 0 {
		return false
	}
	start := 0
	if text[0] == '+' || text[0] == '-' {
		start = 1
	}
	if len(text[start:]) == 0 {
		return false
	}
	if bytes.Equal(text[start:], []byte("Infinity")) || bytes.Equal(text[start:], []byte("NaN")) {
		return false
	}
	if len(text[start:]) >= 2 && text[start] == '0' && (text[start+1] == 'x' || text[start+1] == 'X') {
		return true
	}
	for _, b := range text[start:] {
		if b == '.' || b == 'e' || b == 'E' {
			return false
		}
	}
	return true
}

func (r *goRenderer) renderType(schema *goSchema, suggestedName string) string {
	switch schema.kind {
	case goSchemaBool:
		return "bool"
	case goSchemaInt:
		return "int64"
	case goSchemaFloat:
		return "float64"
	case goSchemaString:
		return "string"
	case goSchemaSlice:
		return "[]" + r.renderType(schema.elem, suggestedName+"Item")
	case goSchemaStruct:
		if name, ok := r.names[schema]; ok {
			return name
		}
		name := r.uniqueTypeName(suggestedName)
		r.names[schema] = name
		declIndex := len(r.decls)
		r.decls = append(r.decls, goTypeDecl{name: name})
		usedFields := make(map[string]int, len(schema.fields))
		for _, field := range schema.fields {
			fieldName := uniqueFieldName(usedFields, goIdentifier(field.key, true))
			typeRef := r.renderType(field.typ, name+fieldName)
			r.decls[declIndex].fields = append(r.decls[declIndex].fields, goRenderedField{
				name:    fieldName,
				typeRef: typeRef,
				tag:     `json:"` + field.key + `"`,
				comment: field.comment,
			})
		}
		return name
	default:
		return "any"
	}
}

func (r *goRenderer) uniqueTypeName(name string) string {
	if name == "" {
		name = "Root"
	}
	count := r.used[name]
	r.used[name] = count + 1
	if count == 0 {
		return name
	}
	return fmt.Sprintf("%s%d", name, count+1)
}

func uniqueFieldName(used map[string]int, name string) string {
	if name == "" {
		name = "Field"
	}
	count := used[name]
	used[name] = count + 1
	if count == 0 {
		return name
	}
	return fmt.Sprintf("%s%d", name, count+1)
}

func goIdentifier(text string, exported bool) string {
	parts := splitIdentifierParts(text)
	if len(parts) == 0 {
		if exported {
			return "Root"
		}
		return "main"
	}
	var buf strings.Builder
	if exported {
		for _, part := range parts {
			buf.WriteString(upperFirst(part))
		}
	} else {
		buf.WriteString(strings.ToLower(parts[0]))
		for _, part := range parts[1:] {
			buf.WriteString(upperFirst(part))
		}
	}
	name := buf.String()
	if name == "" {
		if exported {
			return "Root"
		}
		return "main"
	}
	first, _ := firstRune(name)
	if unicode.IsDigit(first) {
		if exported {
			return "X" + name
		}
		return "x" + name
	}
	if !exported {
		runes := []rune(name)
		runes[0] = unicode.ToLower(runes[0])
		name = string(runes)
	}
	return name
}

func splitIdentifierParts(text string) []string {
	var parts []string
	var buf []rune
	flush := func() {
		if len(buf) == 0 {
			return
		}
		parts = append(parts, strings.ToLower(string(buf)))
		buf = buf[:0]
	}
	for _, r := range text {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			buf = append(buf, r)
			continue
		}
		flush()
	}
	flush()
	return parts
}

func firstRune(s string) (rune, int) {
	for i, r := range s {
		return r, i
	}
	return 0, 0
}

func upperFirst(s string) string {
	runes := []rune(s)
	if len(runes) == 0 {
		return ""
	}
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}
